# gqrx.toml

# Date Time
# offset_date-time     = 2021-01-12 01:23:45+01:00
# offset_date-time_utc = 2021-01-12 00:23:45Z
# local_date-time      = 2021-01-12 01:23:45

[connection-settings]
hostname = "192.168.1.1"
port = 455

[initial-setup]
    freq = 123

[record]
    [record.date_time]
    start = 2021-01-12 01:23:45
    stop = 2021-01-12 01:23:46

    [record.time]
    start = 01:23:45
    stop = 01:23:46

    [record.cron]
    start = "...."
    stop = "..."
