# gqrx.toml
# A file showing valid configuration used for some testing tasks.

########################################################
# IMPORTANT
# !!!DO NOT USE LEADING ZEROS!!!
# WRONG : "minute= 02"
# OK    : "minute= 2"
########################################################

[connection-settings]
    hostname = "localhost"
    port = 7356

[initial-setup]
    commands=["M OFF", "U DSP 0", "F 140000"]

[[task]]
    execution="all"
    commands=["U DSP 1", "U IQRECORD 1"]
    sched_type= "cron"
    hour= 15
    minute= 55

[[task]]
    execution="all"
    commands=["U DSP 0", "U IQRECORD 0"]
    sched_type= "cron"
    hour= 15
    minute= 56

[[task]]
    execution="one_by_one"
    commands=["F 105800000", "F 101000000"]
    sched_type= "cron"
    second= "*/10"
